/**
 * Perk Type String Constants
 *
 * @see source_as_win63/habbo/communication/enum/perk/class_3387.as
 */
export const PerkType = {
	USE_GUIDE_TOOL: 'USE_GUIDE_TOOL',
	GIVE_GUIDE_TOURS: 'GIVE_GUIDE_TOURS',
	JUDGE_CHAT_REVIEWS: 'JUDGE_CHAT_REVIEWS',
	VOTE_IN_COMPETITIONS: 'VOTE_IN_COMPETITIONS',
	CALL_ON_HELPERS: 'CALL_ON_HELPERS',
	CITIZEN: 'CITIZEN',
	TRADE: 'TRADE',
	HEIGHTMAP_EDITOR_BETA: 'HEIGHTMAP_EDITOR_BETA',
	BUILDER_AT_WORK: 'BUILDER_AT_WORK',
	NAVIGATOR_PHASE_ONE_2014: 'NAVIGATOR_PHASE_ONE_2014',
	CAMERA: 'CAMERA',
	NAVIGATOR_PHASE_TWO_2014: 'NAVIGATOR_PHASE_TWO_2014',
	MOUSE_ZOOM: 'MOUSE_ZOOM',
	NAVIGATOR_ROOM_THUMBNAIL_CAMERA: 'NAVIGATOR_ROOM_THUMBNAIL_CAMERA',
	HABBO_CLUB_OFFER_BETA: 'HABBO_CLUB_OFFER_BETA',
} as const;

export type PerkTypeValue = typeof PerkType[keyof typeof PerkType];
