// GENERATED by scripts/extract-flash-text-metrics.mjs — do not edit by hand.
//
// Flash's own single-line text metrics, recovered from the authored heights in
// the shipped window layouts. Each entry is a font size mapped to the line box
// Flash used for it, with the field's 2px top and bottom gutters removed.
//
// Only sizes where the layouts agree are listed: at least 10 single-line
// fields, at least 60% of them on the same height. Everything else falls back to
// measuring the font in the browser, which is what the whole port did before.
//
// TS-only: Flash's metrics lived inside the player; no AS3 source states them.

/** A flash.text.TextField reserves this much above AND below its text. */
export const FLASH_TEXT_GUTTER = 2;

/** font size -> the line box Flash advanced by, gutters excluded. */
export const FLASH_LINE_BOX: ReadonlyMap<number, number> = new Map([
    [9, 10],
    [10, 11],
    [11, 12],
    [12, 13],
    [13, 14],
    [16, 17],
    [18, 20],
    [20, 22],
    [24, 26],
]);

/**
 * Flash's line box for a size, or null when the layouts had nothing confident
 * to say about it.
 */
export function flashLineBox(fontSize: number): number | null
{
    return FLASH_LINE_BOX.get(Math.round(fontSize)) ?? null;
}
