/**
 * Habbo-specific window parameter flags (bitwise).
 *
 * Extends the core WindowParam with Habbo-specific behavior flags.
 * These are OR'd together to create a composite param value.
 *
 * @see sources/win63_version/habbo/window/enum/HabboWindowParam.as
 */
export const HabboWindowParam =
	{
		NULL: 0,
		INPUT_EVENT_PROCESSOR: 1,
		ROUTE_INPUT_EVENTS_TO_PARENT: 3,
		OBSERVE_PARENT_INPUT_EVENTS: 5,
		INTERNAL_EVENT_HANDLING: 9,
		USE_PARENT_GRAPHIC_CONTEXT: 16,
		BOUND_TO_PARENT_RECT: 32,

		RELATIVE_HORIZONTAL_SCALE_FIXED: 0,
		RELATIVE_HORIZONTAL_SCALE_MOVE: 64,
		RELATIVE_HORIZONTAL_SCALE_STRETCH: 128,
		RELATIVE_HORIZONTAL_SCALE_CENTER: 192,
		RELATIVE_HORIZONTAL_SCALE_MASK: 192,

		RELATIVE_VERTICAL_SCALE_FIXED: 0,
		RELATIVE_VERTICAL_SCALE_MOVE: 1024,
		RELATIVE_VERTICAL_SCALE_STRETCH: 2048,
		RELATIVE_VERTICAL_SCALE_CENTER: 3072,
		RELATIVE_VERTICAL_SCALE_MASK: 3072,

		RELATIVE_SCALE_FIXED: 0,
		RELATIVE_SCALE_MOVE: 1088,
		RELATIVE_SCALE_STRETCH: 2176,
		RELATIVE_SCALE_CENTER: 3264,

		ON_RESIZE_ALIGN_LEFT: 0,
		ON_RESIZE_ALIGN_RIGHT: 262144,
		ON_RESIZE_ALIGN_CENTER: 786432,
		ON_RESIZE_ALIGN_TOP: 0,
		ON_RESIZE_ALIGN_BOTTOM: 1048576,
		ON_RESIZE_ALIGN_MIDDLE: 3145728,

		EXPAND_TO_ACCOMMODATE_CHILDREN: 131072,
		RESIZE_TO_ACCOMMODATE_CHILDREN: 147456,

		MOUSE_DRAGGING_TARGET: 32768,
		MOUSE_DRAGGING_TRIGGER: 257,
		DRAGGABLE_WITH_MOUSE: 33025,

		MOUSE_SCALING_TARGET: 65536,
		HORIZONTAL_MOUSE_SCALING_TRIGGER: 4096,
		VERTICAL_MOUSE_SCALING_TRIGGER: 8192,
		MOUSE_SCALING_TRIGGER: 12288,
		MOUSE_SCALING_TRIGGER_MASK: 12288,
		SCALABLE_WITH_MOUSE: 77824,

		PARENT_WINDOW: 1,
		CHILD_WINDOW: 33,
		EMBEDDED_CONTROLLER: 51,

		FORCE_CLIPPING: 1073741824,
	} as const;

export type HabboWindowParamValue = typeof HabboWindowParam[keyof typeof HabboWindowParam];
