/**
 * Window element type identifiers.
 *
 * Each constant maps to a unique numeric type ID used by the window framework
 * to identify the kind of UI element (button, container, frame, etc.).
 *
 * @see sources/win63_2021_version/com/sulake/core/window/enum/_SafeStr_112.as
 */
export const WindowType =
    {
        NULL: 0,
        ICON: 1,
        BACKGROUND: 2,
        CONTAINER: 4,
        REGION: 5,
        HEADER: 6,
        TOOLBAR: 7,
        TOOLTIP: 8,
        NOTIFY: 9,
        TEXT: 10,
        HTML: 11,
        LABEL: 12,
        LINK: 14,
        FORMATTED_TEXT: 15,
        WIDGET: 16,
        BOXSIZER: 17,
        DISPLAY_OBJECT_WRAPPER: 20,
        BITMAP_WRAPPER: 21,
        SHAPE_WRAPPER: 22,
        STATIC_BITMAP_WRAPPER: 23,
        BORDER: 30,
        BORDER_THIN: 31,
        BORDER_THICK: 32,
        BORDER_NOTIFY: 33,
        FRAME: 35,
        FRAME_THIN: 36,
        FRAME_THICK: 37,
        FRAME_NOTIFY: 38,
        ACTIVATOR: 40,
        CONTAINER_BUTTON: 41,
        SELECTOR: 42,
        SELECTOR_LIST: 43,
        BUBBLE: 45,
        BUBBLE_POINTER_UP: 46,
        BUBBLE_POINTER_RIGHT: 47,
        BUBBLE_POINTER_DOWN: 48,
        BUBBLE_POINTER_LEFT: 49,
        ITEMLIST: 50,
        ITEMLIST_VERTICAL: 50,
        ITEMLIST_HORIZONTAL: 51,
        ITEMGRID: 52,
        ITEMGRID_VERTICAL: 53,
        ITEMGRID_HORIZONTAL: 54,
        SCROLLABLE_ITEMLIST: 55,
        SCROLLABLE_ITEMLIST_VERTICAL: 56,
        SCROLLABLE_ITEMLIST_HORIZONTAL: 57,
        BUTTON: 60,
        BUTTON_THICK: 61,
        BUTTON_ICON: 62,
        BUTTON_UP: 63,
        BUTTON_DOWN: 64,
        BUTTON_LEFT: 65,
        BUTTON_RIGHT: 66,
        BUTTON_GROUP_LEFT: 67,
        BUTTON_GROUP_CENTER: 68,
        BUTTON_GROUP_RIGHT: 69,
        CHECKBOX: 70,
        RADIOBUTTON: 71,
        CLOSEBUTTON: 72,
        MINIMIZEBOX: 73,
        MAXIMIZEBOX: 74,
        RESTOREBOX: 75,
        DRAGBAR: 76,
        TEXTFIELD: 77,
        PASSWORD: 78,
        TAB_CONTENT: 90,
        TAB_CONTEXT: 91,
        TAB_SELECTOR: 92,
        TAB_BUTTON: 93,
        TAB_CONTAINER_BUTTON: 94,
        MENU: 100,
        MENU_ITEM: 101,
        DROPMENU: 102,
        DROPMENU_ITEM: 103,
        SUBMENU: 104,
        DROPLIST: 105,
        DROPLIST_ITEM: 106,
        SLIDER: 110,
        SLIDER_HORIZONTAL: 111,
        SLIDER_VERTICAL: 112,
        SCALER: 120,
        SCALER_VERTICAL: 121,
        SCALER_HORIZONTAL: 122,
        SCROLLBAR_HORIZONTAL: 130,
        SCROLLBAR_VERTICAL: 131,
        SCROLLBAR_SLIDER_BAR_HORIZONTAL: 132,
        SCROLLBAR_SLIDER_BAR_VERTICAL: 133,
        SCROLLBAR_SLIDER_TRACK_HORIZONTAL: 134,
        SCROLLBAR_SLIDER_TRACK_VERTICAL: 135,
        SCROLLBAR_SLIDER_BUTTON_RIGHT: 136,
        SCROLLBAR_SLIDER_BUTTON_DOWN: 137,
        SCROLLBAR_SLIDER_BUTTON_LEFT: 138,
        SCROLLBAR_SLIDER_BUTTON_UP: 139,
        SCROLLABLE_ITEMGRID_VERTICAL: 140,
    } as const;

export type WindowTypeValue = typeof WindowType[keyof typeof WindowType];

/**
 * Map element tag name to type ID.
 * Used at build time and runtime to resolve XML/JSON tag names.
 *
 * @see sources/win63_2021_version/com/sulake/core/window/utils/TypeCodeTable.as
 */
export const TYPE_NAME_TO_CODE: Record<string, number> =
    {
        'null': WindowType.NULL,
        'icon': WindowType.ICON,
        'background': WindowType.BACKGROUND,
        'container': WindowType.CONTAINER,
        'region': WindowType.REGION,
        'header': WindowType.HEADER,
        'toolbar': WindowType.TOOLBAR,
        'tooltip': WindowType.TOOLTIP,
        'notify': WindowType.NOTIFY,
        'text': WindowType.TEXT,
        'html': WindowType.HTML,
        'label': WindowType.LABEL,
        'link': WindowType.LINK,
        'formatted_text': WindowType.FORMATTED_TEXT,
        'widget': WindowType.WIDGET,
        'boxsizer': WindowType.BOXSIZER,
        'display_object_wrapper': WindowType.DISPLAY_OBJECT_WRAPPER,
        'bitmap': WindowType.BITMAP_WRAPPER,
        'shape_wrapper': WindowType.SHAPE_WRAPPER,
        'static_bitmap': WindowType.STATIC_BITMAP_WRAPPER,
        'border': WindowType.BORDER,
        'border_thin': WindowType.BORDER_THIN,
        'border_thick': WindowType.BORDER_THICK,
        'border_notify': WindowType.BORDER_NOTIFY,
        'frame': WindowType.FRAME,
        'frame_thin': WindowType.FRAME_THIN,
        'frame_thick': WindowType.FRAME_THICK,
        'frame_notify': WindowType.FRAME_NOTIFY,
        'activator': WindowType.ACTIVATOR,
        'container_button': WindowType.CONTAINER_BUTTON,
        'selector': WindowType.SELECTOR,
        'selector_list': WindowType.SELECTOR_LIST,
        'bubble': WindowType.BUBBLE,
        'bubble_pointer_up': WindowType.BUBBLE_POINTER_UP,
        'bubble_pointer_right': WindowType.BUBBLE_POINTER_RIGHT,
        'bubble_pointer_down': WindowType.BUBBLE_POINTER_DOWN,
        'bubble_pointer_left': WindowType.BUBBLE_POINTER_LEFT,
        'itemlist': WindowType.ITEMLIST,
        'itemlist_vertical': WindowType.ITEMLIST_VERTICAL,
        'itemlist_horizontal': WindowType.ITEMLIST_HORIZONTAL,
        'itemgrid': WindowType.ITEMGRID,
        'itemgrid_vertical': WindowType.ITEMGRID_VERTICAL,
        'itemgrid_horizontal': WindowType.ITEMGRID_HORIZONTAL,
        'scrollable_itemlist': WindowType.SCROLLABLE_ITEMLIST,
        'scrollable_itemlist_vertical': WindowType.SCROLLABLE_ITEMLIST_VERTICAL,
        'scrollable_itemlist_horizontal': WindowType.SCROLLABLE_ITEMLIST_HORIZONTAL,
        'button': WindowType.BUTTON,
        'button_thick': WindowType.BUTTON_THICK,
        'button_icon': WindowType.BUTTON_ICON,
        'button_up': WindowType.BUTTON_UP,
        'button_down': WindowType.BUTTON_DOWN,
        'button_left': WindowType.BUTTON_LEFT,
        'button_right': WindowType.BUTTON_RIGHT,
        'button_group_left': WindowType.BUTTON_GROUP_LEFT,
        'button_group_center': WindowType.BUTTON_GROUP_CENTER,
        'button_group_right': WindowType.BUTTON_GROUP_RIGHT,
        'checkbox': WindowType.CHECKBOX,
        'radiobutton': WindowType.RADIOBUTTON,
        'closebutton': WindowType.CLOSEBUTTON,
        'minimizebox': WindowType.MINIMIZEBOX,
        'maximizebox': WindowType.MAXIMIZEBOX,
        'restorebox': WindowType.RESTOREBOX,
        'dragbar': WindowType.DRAGBAR,
        'input': WindowType.TEXTFIELD,
        'password': WindowType.PASSWORD,
        'tab_content': WindowType.TAB_CONTENT,
        'tab_context': WindowType.TAB_CONTEXT,
        'tab_selector': WindowType.TAB_SELECTOR,
        'tab_button': WindowType.TAB_BUTTON,
        'tab_container_button': WindowType.TAB_CONTAINER_BUTTON,
        'menu': WindowType.MENU,
        'menu_item': WindowType.MENU_ITEM,
        'dropmenu': WindowType.DROPMENU,
        'dropmenu_item': WindowType.DROPMENU_ITEM,
        'submenu': WindowType.SUBMENU,
        'droplist': WindowType.DROPLIST,
        'droplist_item': WindowType.DROPLIST_ITEM,
        'slider': WindowType.SLIDER,
        'slider_horizontal': WindowType.SLIDER_HORIZONTAL,
        'slider_vertical': WindowType.SLIDER_VERTICAL,
        'scaler': WindowType.SCALER,
        'scaler_vertical': WindowType.SCALER_VERTICAL,
        'scaler_horizontal': WindowType.SCALER_HORIZONTAL,
        'scrollbar_horizontal': WindowType.SCROLLBAR_HORIZONTAL,
        'scrollbar_vertical': WindowType.SCROLLBAR_VERTICAL,
        'scrollbar_slider_bar_horizontal': WindowType.SCROLLBAR_SLIDER_BAR_HORIZONTAL,
        'scrollbar_slider_bar_vertical': WindowType.SCROLLBAR_SLIDER_BAR_VERTICAL,
        'scrollbar_slider_track_horizontal': WindowType.SCROLLBAR_SLIDER_TRACK_HORIZONTAL,
        'scrollbar_slider_track_vertical': WindowType.SCROLLBAR_SLIDER_TRACK_VERTICAL,
        'scrollbar_slider_button_right': WindowType.SCROLLBAR_SLIDER_BUTTON_RIGHT,
        'scrollbar_slider_button_down': WindowType.SCROLLBAR_SLIDER_BUTTON_DOWN,
        'scrollbar_slider_button_left': WindowType.SCROLLBAR_SLIDER_BUTTON_LEFT,
        'scrollbar_slider_button_up': WindowType.SCROLLBAR_SLIDER_BUTTON_UP,
        'scrollable_itemgrid_vertical': WindowType.SCROLLABLE_ITEMGRID_VERTICAL,
    };

/**
 * Reverse map: type ID -> element tag name.
 */
export const TYPE_CODE_TO_NAME: Record<number, string> = Object.fromEntries(
    Object.entries(TYPE_NAME_TO_CODE).map(([name, id]) => [id, name])
);
