// Auto-generated barrel file — do not edit manually
// Generated by Barrel Index Generator

export {InstantMessageEventHandler} from './InstantMessageEventHandler';
export {InstantMessageRegistry} from './InstantMessageRegistry';
export {InstantMessageRegistryItem} from './InstantMessageRegistryItem';
