// Auto-generated barrel file — do not edit manually
// Generated by Barrel Index Generator

export {FurnitureItem} from './FurnitureItem';
export {GroupItem} from './GroupItem';
export * from './stuffdata';

// Types
export type {IFurnitureItemData} from './FurnitureItemData';
export type {IFurnitureItem} from './IFurnitureItem';
export type {IStuffData} from './IStuffData';
