/**
 * Window element type identifiers.
 *
 * Each constant maps to a unique numeric type ID used by the window framework
 * to identify the kind of UI element (button, container, frame, etc.).
 *
 * @see sources/PRODUCTION-201601012205-226667486/com/sulake/core/window/enum/WindowType.as
 * @see sources/PRODUCTION-201601012205-226667486/com/sulake/core/window/utils/TypeCodeTable.as
 */
export const WindowElementType =
    {
        NULL: 0,
        ICON: 1,
        BACKGROUND: 2,
        CONTAINER: 4,
        REGION: 5,
        HEADER: 6,
        TOOLBAR: 7,
        TOOLTIP: 8,
        NOTIFY: 9,
        TEXT: 10,
        HTML: 11,
        LABEL: 12,
        LINK: 14,
        FORMATTED_TEXT: 15,
        WIDGET: 16,
        BOXSIZER: 17,
        DISPLAY_OBJECT_WRAPPER: 20,
        BITMAP_WRAPPER: 21,
        SHAPE_WRAPPER: 22,
        STATIC_BITMAP_WRAPPER: 23,
        BORDER: 30,
        BORDER_THIN: 31,
        BORDER_THICK: 32,
        BORDER_NOTIFY: 33,
        FRAME: 35,
        FRAME_THIN: 36,
        FRAME_THICK: 37,
        FRAME_NOTIFY: 38,
        ACTIVATOR: 40,
        CONTAINER_BUTTON: 41,
        SELECTOR: 42,
        SELECTOR_LIST: 43,
        BUBBLE: 45,
        BUBBLE_POINTER_UP: 46,
        BUBBLE_POINTER_RIGHT: 47,
        BUBBLE_POINTER_DOWN: 48,
        BUBBLE_POINTER_LEFT: 49,
        ITEMLIST: 50,
        ITEMLIST_VERTICAL: 50,
        ITEMLIST_HORIZONTAL: 51,
        ITEMGRID: 52,
        ITEMGRID_VERTICAL: 53,
        ITEMGRID_HORIZONTAL: 54,
        SCROLLABLE_ITEMLIST: 55,
        SCROLLABLE_ITEMLIST_VERTICAL: 56,
        SCROLLABLE_ITEMLIST_HORIZONTAL: 57,
        BUTTON: 60,
        BUTTON_THICK: 61,
        BUTTON_ICON: 62,
        BUTTON_UP: 63,
        BUTTON_DOWN: 64,
        BUTTON_LEFT: 65,
        BUTTON_RIGHT: 66,
        BUTTON_GROUP_LEFT: 67,
        BUTTON_GROUP_CENTER: 68,
        BUTTON_GROUP_RIGHT: 69,
        CHECKBOX: 70,
        RADIOBUTTON: 71,
        CLOSEBUTTON: 72,
        MINIMIZEBOX: 73,
        MAXIMIZEBOX: 74,
        RESTOREBOX: 75,
        DRAGBAR: 76,
        TEXTFIELD: 77,
        PASSWORD: 78,
        TAB_CONTENT: 90,
        TAB_CONTEXT: 91,
        TAB_SELECTOR: 92,
        TAB_BUTTON: 93,
        TAB_CONTAINER_BUTTON: 94,
        MENU: 100,
        MENU_ITEM: 101,
        DROPMENU: 102,
        DROPMENU_ITEM: 103,
        SUBMENU: 104,
        DROPLIST: 105,
        DROPLIST_ITEM: 106,
        SLIDER: 110,
        SLIDER_HORIZONTAL: 111,
        SLIDER_VERTICAL: 112,
        SCALER: 120,
        SCALER_VERTICAL: 121,
        SCALER_HORIZONTAL: 122,
        SCROLLBAR_HORIZONTAL: 130,
        SCROLLBAR_VERTICAL: 131,
        SCROLLBAR_SLIDER_BAR_HORIZONTAL: 132,
        SCROLLBAR_SLIDER_BAR_VERTICAL: 133,
        SCROLLBAR_SLIDER_TRACK_HORIZONTAL: 134,
        SCROLLBAR_SLIDER_TRACK_VERTICAL: 135,
        SCROLLBAR_SLIDER_BUTTON_RIGHT: 136,
        SCROLLBAR_SLIDER_BUTTON_DOWN: 137,
        SCROLLBAR_SLIDER_BUTTON_LEFT: 138,
        SCROLLBAR_SLIDER_BUTTON_UP: 139,
        SCROLLABLE_ITEMGRID_VERTICAL: 140,
    } as const;

export type WindowElementTypeValue = typeof WindowElementType[keyof typeof WindowElementType];

/**
 * Map element tag name to type ID.
 * Used at build time and runtime to resolve XML/JSON tag names.
 *
 * @see sources/PRODUCTION-201601012205-226667486/com/sulake/core/window/utils/TypeCodeTable.as
 */
export const ELEMENT_NAME_TO_TYPE: Record<string, number> =
    {
        'null': WindowElementType.NULL,
        'icon': WindowElementType.ICON,
        'background': WindowElementType.BACKGROUND,
        'container': WindowElementType.CONTAINER,
        'region': WindowElementType.REGION,
        'header': WindowElementType.HEADER,
        'toolbar': WindowElementType.TOOLBAR,
        'tooltip': WindowElementType.TOOLTIP,
        'notify': WindowElementType.NOTIFY,
        'text': WindowElementType.TEXT,
        'html': WindowElementType.HTML,
        'label': WindowElementType.LABEL,
        'link': WindowElementType.LINK,
        'formatted_text': WindowElementType.FORMATTED_TEXT,
        'widget': WindowElementType.WIDGET,
        'boxsizer': WindowElementType.BOXSIZER,
        'display_object_wrapper': WindowElementType.DISPLAY_OBJECT_WRAPPER,
        'bitmap': WindowElementType.BITMAP_WRAPPER,
        'shape_wrapper': WindowElementType.SHAPE_WRAPPER,
        'static_bitmap': WindowElementType.STATIC_BITMAP_WRAPPER,
        'border': WindowElementType.BORDER,
        'border_thin': WindowElementType.BORDER_THIN,
        'border_thick': WindowElementType.BORDER_THICK,
        'border_notify': WindowElementType.BORDER_NOTIFY,
        'frame': WindowElementType.FRAME,
        'frame_thin': WindowElementType.FRAME_THIN,
        'frame_thick': WindowElementType.FRAME_THICK,
        'frame_notify': WindowElementType.FRAME_NOTIFY,
        'activator': WindowElementType.ACTIVATOR,
        'container_button': WindowElementType.CONTAINER_BUTTON,
        'selector': WindowElementType.SELECTOR,
        'selector_list': WindowElementType.SELECTOR_LIST,
        'bubble': WindowElementType.BUBBLE,
        'bubble_pointer_up': WindowElementType.BUBBLE_POINTER_UP,
        'bubble_pointer_right': WindowElementType.BUBBLE_POINTER_RIGHT,
        'bubble_pointer_down': WindowElementType.BUBBLE_POINTER_DOWN,
        'bubble_pointer_left': WindowElementType.BUBBLE_POINTER_LEFT,
        'itemlist': WindowElementType.ITEMLIST,
        'itemlist_vertical': WindowElementType.ITEMLIST_VERTICAL,
        'itemlist_horizontal': WindowElementType.ITEMLIST_HORIZONTAL,
        'itemgrid': WindowElementType.ITEMGRID,
        'itemgrid_vertical': WindowElementType.ITEMGRID_VERTICAL,
        'itemgrid_horizontal': WindowElementType.ITEMGRID_HORIZONTAL,
        'scrollable_itemlist': WindowElementType.SCROLLABLE_ITEMLIST,
        'scrollable_itemlist_vertical': WindowElementType.SCROLLABLE_ITEMLIST_VERTICAL,
        'scrollable_itemlist_horizontal': WindowElementType.SCROLLABLE_ITEMLIST_HORIZONTAL,
        'button': WindowElementType.BUTTON,
        'button_thick': WindowElementType.BUTTON_THICK,
        'button_icon': WindowElementType.BUTTON_ICON,
        'button_up': WindowElementType.BUTTON_UP,
        'button_down': WindowElementType.BUTTON_DOWN,
        'button_left': WindowElementType.BUTTON_LEFT,
        'button_right': WindowElementType.BUTTON_RIGHT,
        'button_group_left': WindowElementType.BUTTON_GROUP_LEFT,
        'button_group_center': WindowElementType.BUTTON_GROUP_CENTER,
        'button_group_right': WindowElementType.BUTTON_GROUP_RIGHT,
        'checkbox': WindowElementType.CHECKBOX,
        'radiobutton': WindowElementType.RADIOBUTTON,
        'closebutton': WindowElementType.CLOSEBUTTON,
        'minimizebox': WindowElementType.MINIMIZEBOX,
        'maximizebox': WindowElementType.MAXIMIZEBOX,
        'restorebox': WindowElementType.RESTOREBOX,
        'dragbar': WindowElementType.DRAGBAR,
        'input': WindowElementType.TEXTFIELD,
        'password': WindowElementType.PASSWORD,
        'tab_content': WindowElementType.TAB_CONTENT,
        'tab_context': WindowElementType.TAB_CONTEXT,
        'tab_selector': WindowElementType.TAB_SELECTOR,
        'tab_button': WindowElementType.TAB_BUTTON,
        'tab_container_button': WindowElementType.TAB_CONTAINER_BUTTON,
        'menu': WindowElementType.MENU,
        'menu_item': WindowElementType.MENU_ITEM,
        'dropmenu': WindowElementType.DROPMENU,
        'dropmenu_item': WindowElementType.DROPMENU_ITEM,
        'submenu': WindowElementType.SUBMENU,
        'droplist': WindowElementType.DROPLIST,
        'droplist_item': WindowElementType.DROPLIST_ITEM,
        'slider': WindowElementType.SLIDER,
        'slider_horizontal': WindowElementType.SLIDER_HORIZONTAL,
        'slider_vertical': WindowElementType.SLIDER_VERTICAL,
        'scaler': WindowElementType.SCALER,
        'scaler_vertical': WindowElementType.SCALER_VERTICAL,
        'scaler_horizontal': WindowElementType.SCALER_HORIZONTAL,
        'scrollbar_horizontal': WindowElementType.SCROLLBAR_HORIZONTAL,
        'scrollbar_vertical': WindowElementType.SCROLLBAR_VERTICAL,
        'scrollbar_slider_bar_horizontal': WindowElementType.SCROLLBAR_SLIDER_BAR_HORIZONTAL,
        'scrollbar_slider_bar_vertical': WindowElementType.SCROLLBAR_SLIDER_BAR_VERTICAL,
        'scrollbar_slider_track_horizontal': WindowElementType.SCROLLBAR_SLIDER_TRACK_HORIZONTAL,
        'scrollbar_slider_track_vertical': WindowElementType.SCROLLBAR_SLIDER_TRACK_VERTICAL,
        'scrollbar_slider_button_right': WindowElementType.SCROLLBAR_SLIDER_BUTTON_RIGHT,
        'scrollbar_slider_button_down': WindowElementType.SCROLLBAR_SLIDER_BUTTON_DOWN,
        'scrollbar_slider_button_left': WindowElementType.SCROLLBAR_SLIDER_BUTTON_LEFT,
        'scrollbar_slider_button_up': WindowElementType.SCROLLBAR_SLIDER_BUTTON_UP,
        'scrollable_itemgrid_vertical': WindowElementType.SCROLLABLE_ITEMGRID_VERTICAL,
    };

/**
 * Reverse map: type ID -> element tag name.
 */
export const ELEMENT_TYPE_TO_NAME: Record<number, string> = Object.fromEntries(
    Object.entries(ELEMENT_NAME_TO_TYPE).map(([name, id]) => [id, name])
);
