// Auto-generated barrel file — do not edit manually
// Generated by Barrel Index Generator

// Exports
export {CoreLocalizationManager} from './CoreLocalizationManager';
export {GameDataResources} from './GameDataResources';
export {Localization} from './Localization';
export {LocalizationDefinition} from './LocalizationDefinition';
export {LocalizationEvent} from './LocalizationEvent';

// Types
export type {LocalizationManagerEvents, ICoreLocalizationManager,} from './ICoreLocalizationManager';
export type {IGameDataResources} from './IGameDataResources';
export type {ILocalizable} from './ILocalizable';
export type {ILocalization} from './ILocalization';
export type {ILocalizationDefinition} from './ILocalizationDefinition';
export type {LocalizationEventType} from './LocalizationEvent';
