/**
 * Navigator tracking event constants
 *
 * Based on AS3 com.sulake.habbo.navigator.events.HabboNavigatorTrackingEvent
 */
export const HabboNavigatorTrackingEvent = {
	CLOSED: 'HABBO_NAVIGATOR_TRACKING_EVENT_CLOSED',
	EVENTS: 'HABBO_NAVIGATOR_TRACKING_EVENT_EVENTS',
	ROOMS: 'HABBO_NAVIGATOR_TRACKING_EVENT_ROOMS',
	ME: 'HABBO_NAVIGATOR_TRACKING_EVENT_ME',
	SEARCH: 'HABBO_NAVIGATOR_TRACKING_EVENT_SEARCH',
	OFFICIAL: 'HABBO_NAVIGATOR_TRACKING_EVENT_OFFICIAL',
	CATEGORIES: 'HABBO_NAVIGATOR_TRACKING_EVENT_CATEGORIES',
	SEARCHTYPE_MY_FAVOURITES: 'HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FAVOURITES',
	SEARCHTYPE_MY_FRIENDS_ROOMS: 'HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FRIENDS_ROOMS',
	SEARCHTYPE_MY_HISTORY: 'HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_HISTORY',
	SEARCHTYPE_MY_ROOMS: 'HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_ROOMS',
	SEARCHTYPE_OFFICIALROOMS: 'HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_OFFICIALROOMS',
	SEARCHTYPE_POPULAR_ROOMS: 'HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_POPULAR_ROOMS',
	SEARCHTYPE_ROOMS_WHERE_MY_FRIENDS_ARE: 'HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_ROOMS_WHERE_MY_FRIENDS_ARE',
	SEARCHTYPE_ROOMS_WITH_HIGHEST_SCORE: 'HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_ROOMS_WITH_HIGHEST_SCORE',
	SEARCHTYPE_TAG_SEARCH: 'HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_TAG_SEARCH',
	SEARCHTYPE_TEXT_SEARCH: 'HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_TEXT_SEARCH',
	SEARCHTYPE_MY_FREQUENT_HISTORY: 'HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FREQUENT_HISTORY',
} as const;

export type HabboNavigatorTrackingEventType = (typeof HabboNavigatorTrackingEvent)[keyof typeof HabboNavigatorTrackingEvent];
