// Auto-generated barrel file — do not edit manually
// Generated by Barrel Index Generator

export {FurnitureCategory} from './FurnitureCategory';
export {UnseenItemCategory, INVENTORY_CATEGORIES,} from './UnseenItemCategory';

// Types
export type {FurnitureCategoryType} from './FurnitureCategory';
export type {UnseenItemCategoryType} from './UnseenItemCategory';
